### ISSUE TITLE
dont work with long type

### ISSUE THREAD

**Issue by mokashahar** [garvincasimir/csharp-datatables-parser#13]
Just notice that if the coloum typs is long the search function dont work right

**Comment by garvincasimir** [comment]
We should be able to add long as a searchable type. I will look into it.

**Comment by mokashahar** [comment]
Good to hear! please update me soon as it happens

**Comment by garvincasimir** [comment]
The latest update includes support for the long data type. If you are using NuGet you can simply update your package. If not, update your solution with the file from the latest master.
