### ISSUE TITLE
Consider using Future Queries to reduce roundtrips to database

### ISSUE THREAD

**Issue by jmo21** [garvincasimir/csharp-datatables-parser#16]
Please consider using Future Queries (https://github.com/loresoft/EntityFramework.Extended/wiki/Future-Queries) to reduce the database hits from 2 to 1 when using Entity Framework branch of https://github.com/garvincasimir/csharp-datatables-parser/blob/master/DatatablesParser/DatatablesParser.cs

**Comment by garvincasimir** [comment]
Yes the multiple calls to the database bother me as well. 

I attempted to implement the library you linked to but unfortunately my tests failed with an exception. I found the exception on an open issue in the project but there is no indication that this project is being maintained/supported. I don't have time to figure out the problem.

Going deeper into the issue I would say that the cost of the extra round trip is negligible and the added complexity of any solution to avoid it might not be worth the gains. That is of course going on the assumption that your database is properly tuned.
