### ISSUE TITLE
Getting error 505

### ISSUE THREAD

**Issue by arbh89** [garvincasimir/csharp-datatables-parser#18]
Thanks for your awesome work, i am getting error 

**Server Error in '/' Application.**

**Value cannot be null.**
**Parameter name: String**

When using nuget package **C# DataTables.net Parser 3.0.0** and **Datatables plugin 1.10.11**

If i use the code from this repo everithing works fine, seems like nuget package is outdated.

**Comment by garvincasimir** [comment]
That sounds very strange. You should turn on detailed error reporting and get a stack trace. Where is this error coming from?

**Comment by arbh89** [comment]
The problem is that nuget package is outdated, i have decompiled dll from nuget and is different than code from this repo.

**Comment by garvincasimir** [comment]
Ok I will recreate the NuGet package.

**Comment by garvincasimir** [comment]
I just did a sync and created a new package v3.0.1. Give it some time to index and appear in your list of upgrades. Please let me know if you encounter any further issues.

**Comment by arbh89** [comment]
I have downloaded version 3.0.1 but it  is not updated code looks like this decompiled.

```c#
public class DataTablesParser<T> where T : class
	{
		private class PropertyMapping
		{
			public PropertyInfo Property
			{
				get;
				set;
			}
			public bool Sortable
			{
				get;
				set;
			}
			public bool Searchable
			{
				get;
				set;
			}
		}
		private const string INDIVIDUAL_DATA_KEY_PREFIX = "mDataProp_";
		private const string INDIVIDUAL_SEARCH_KEY_PREFIX = "sSearch_";
		private const string INDIVIDUAL_SEARCHABLE_KEY_PREFIX = "bSearchable_";
		private const string INDIVIDUAL_SORTABLE_KEY_PREFIX = "bSortable_";
		private const string INDIVIDUAL_SORT_KEY_PREFIX = "iSortCol_";
		private const string INDIVIDUAL_SORT_DIRECTION_KEY_PREFIX = "sSortDir_";
		private const string DISPLAY_START = "iDisplayStart";
		private const string DISPLAY_LENGTH = "iDisplayLength";
		private const string ECHO = "sEcho";
		private const string ASCENDING_SORT = "asc";
```
As you can see, is using old datatables variables.

**Comment by garvincasimir** [comment]
So funny story. I have another repo which automatically copies the new build artifacts to the nuget package. I forgot that this is an older one where I copied the dll over manually.

**Comment by garvincasimir** [comment]
@arbh89 does it work now?

**Comment by arbh89** [comment]
Yes, it is working now, thank you.
