### ISSUE TITLE
Remove property.CanWrite requirement to allow better global searching

### ISSUE THREAD

**Issue by kmd1970** [garvincasimir/csharp-datatables-parser#25]
If you remove the `property.CanWrite ` (line 251) requirement, then you can search by any custom (string) properties you create like `BirthDateFormatted`. This solves the issue of global searching non string properties. 

Also, you can specify different property name for sorting, searching, displaying the same column data:
```js
columns: [
 { data: "FirstName", title: "First Name" },
 { data: "LastName", title: "Last Name" },
 { data: { "_" : ""BirthDateFormatted", sort : "BirthDate", filter: "BirthDateFormatted" } , title: "Birth Date" , orderData : 3}
]
```
https://datatables.net/reference/option/columns.data#object

**Comment by garvincasimir** [comment]
@kmd1970 Thanks for bringing this up. I should add a section for this in the docs.

To answer your question, if I remove property.CanWrite, filtering for queryables backed by a database will break. The expressions generated by the filter function eventually get translated to a sql query against the table mapped to your model. To reference your example, BirthDateFormatted is not a field in the people table so it cannot be included in the query.

If you would like BirthDateFormatted to be included in your filter, send in a queryable backed by in-memory data. I would only recommend this for small datasets.

`var parser = new Parser<Person>(p, context.People.ToList().AsQueryable()); `

I plan to experiment with allowing library users to provide custom date and numeric type format strings to the parser. This new functionality would reduce the need for a separate custom format property. It may come in the form of attributes or a fluent API. Ultimately, whatever is generated needs to be translated into sql and supported by the ORM (entity framework), query provider,  and database engine.

**Comment by kmd1970** [comment]
@garvincasimir  Sorry, I forgot about the "translated into sql" part. 

I've written Datatable parsers for other systems and it has always been easier convert all non string columns to string for easier global searching. 

Also, in other coding environments you can call sql server user defined functions and use calculated values in your SQL select and where clauses. I can't seem to figure out how to do this in entity framework and .NET.

**Comment by garvincasimir** [comment]
@kmd1970  I assume your other implementations allowed you to write the exact sql statements you needed for your use case and db engine. This is possible in .net using ADO.net:
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ado-net-code-examples#adonet-data-provider-examples

You can use the same strategy/algorithms from your other Datatable implementations since ADO.net will allow you to write your own sql statements.

**Comment by garvincasimir** [comment]
@kmd1970 The parser now has support for user defined functions in filter expressions. Please take a look at the Readme and let me know if it resolves your issue.

**Comment by kmd1970** [comment]
@garvincasimir Looks great, I will take a look. Thanks.
