### ISSUE TITLE
Add feature for nested search ?

### ISSUE THREAD

**Issue by fachrihawari** [garvincasimir/csharp-datatables-parser#28]
Thanks for awesome package, you save my time.
I have suggestion for nested search, because sometime i have nested query like below.
![image](https://user-images.githubusercontent.com/11810256/32636467-82dcbed2-c5e7-11e7-9fbf-2861cd6acd88.png)

**Comment by garvincasimir** [comment]
If you use a projection and map it to a nested field, nested search should work. I am not sure if this is what you are looking for. Currently, the library only searches properties that are members of the generic type you use to initialize the parser. You can use any type as long as it is also in the projection. 

```c#
var result = select d from _context.Data 
                    select new DataResult 
                    {
                              FieldA = d.FieldA,
                              FieldB = d.KindType.FieldC
                     } ;  

var parser = new Parser<DataResult>(Request.Form,result);                     
```
I hope this helps. 

By the way, what version are you using? The latest?

**Comment by garvincasimir** [comment]
I just realized that all the samples use the model class directly in the parser. In my own code I only every do it with a plain class like I showed you in my previous example.

**Comment by fachrihawari** [comment]
Thanks again, i try like code below and its work.
```csharp
IQueryable<DataTableResult> mapped = _context.Data.Select(d => new DataTableResult {
    title = string.Format(
        "{0} - {1} - {2} - {3} - {4}", 
        d.KindType.DepartmentKind.CategoryDepartment.Category.Name,
        d.KindType.DepartmentKind.CategoryDepartment.Department.Description,
        d.KindType.DepartmentKind.Kind.Name,
        d.KindType.Type.Name,
        d.KindType.Time.Name
    ),
    time = d.Time,
    pdfName = d.PdfName,
    id = d.Id
}).AsQueryable<DataTableResult>();

var parser = new Parser<DataTableResult>(Request.Form, mapped);

return Json(parser.Parse());

```
May be you must make your readme.md more clear for the feature and how to use your package 😄

**Comment by garvincasimir** [comment]
I will definitely include something on this in the docs. Be careful here because being forced to call AsQueryable<T> almost always means you just pulled all your data into memory. You want to avoid that. There is no sql translation for string.Format so please concat the string yourself.

```csharp

var mapped = from d in _context.Data
      let title = d.KindType.DepartmentKind.CategoryDepartment.Category.Name + " - " + d.KindType.DepartmentKind.CategoryDepartment.Department.Description + " - " + d.KindType.DepartmentKind.Kind.Name + " - " +  d.KindType.Type.Name +  " - " +  d.KindType.Time.Name

select new DataTableResult
{
    title = title,
    time = d.Time,
    pdfName = d.PdfName,
    id = d.Id
};

var parser = new Parser<DataTableResult>(Request.Form, mapped);

return Json(parser.Parse());
```

**Comment by fachrihawari** [comment]
Okay, Thanks for your suggestion
