### ISSUE TITLE
Multi filter select

### ISSUE THREAD

**Issue by fachrihawari** [garvincasimir/csharp-datatables-parser#29]
I try to implement [DataTable multi filter select](https://datatables.net/examples/api/multi_filter_select.html) with your plugin. 

below is javascript code
```javascript
$(document).ready(function() {
    $('#example').DataTable( {
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );

                       //-- highlight code
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                       //-- highlight code


                    } );
 
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
```

C# code
```cs
public IActionResult ProductData()
{
    var aMPOSContext = _context.Products
                        .Include(p => p.Manufacture)
                        .Include(p => p.ProductCategory)
                        .AsQueryable();            

    var parser = new Parser<Product>(Request.Form, aMPOSContext);

    return Json(parser.Parse());
}
```

I filter column like picture below with code P0001, i didn't get any data
![image](https://user-images.githubusercontent.com/11810256/37198031-733ac188-23af-11e8-808d-f0e8a33821d3.png)

After that i try change javascript code from
```javascript
column.search( val ? '^'+val+'$' : '', true, false ).draw();
```
change to 
```javascript
column.search( val ? val: '', true, false ).draw();
```
Now the data has appeared but not as I expected.
It should be displayed only data with Code P0001 but the data seems to follow conditions like %P0001%

is the feature for filter by select tag already available?

**Comment by garvincasimir** [comment]
Unfortunately, the library does not support regex based filtering. So all searches are %searchterm%. What database engine are you using? Not all DBs support regex filtering. I don't have a good way to detect the db engine or support for translatable APIs so the best I can do is allow regex filtering for object based (in memory) queries. This means you will have to call .ToList().AsQueryable() before passing your query to the parser. Will that work?

**Comment by fachrihawari** [comment]
I use SQL Server. 
Okay i will try your suggestion later

**Comment by garvincasimir** [comment]
The ToList() option is not available right now. It is something I would have to implement in the code because right now I ignore the regex request parameters.

**Comment by scbrady** [comment]
@garvincasimir I just ran into this same issue, and I am already using the `.ToList().AsQueryable()` method. I'd love for this functionality to be added in. Is this something you would accept a pull request for?

**Comment by garvincasimir** [comment]
Yes @scbrady, I would accept a pull request. It has to be done in a way that doesn't introduce errors for platforms that do not support it.
