### ISSUE TITLE
Error on parsing

### ISSUE THREAD

**Issue by arbh89** [garvincasimir/csharp-datatables-parser#30]
Hi, i am getting the following error on parsing.

LINQ to Entities does not recognize the method 'System.String ToString()' method, and this method cannot be translated into a store expression.

**Comment by arbh89** [comment]
I am using latest version with EF6 and SQL2014 express, i am not using any custom expression, i am trying to use in a webform project with web api 2 .net framework 4.6.1.

**Comment by garvincasimir** [comment]
Ah I think I misunderstood your error. 

We must convert all non string properties to a string before we apply the filter. EF6 does not support ToString() on numeric and date types. If your generic parameter *T* contains numeric or date types you will get errors when attempting to apply a filter. You should be able to get around this by using SqlFunctions in a custom expression.

```csharp
//Property Age is a number
var parser = new Parser<Person>(p, context.People)
                  .SetConverter(x => x.Age, x => SqlFunctions.StringConvert(x.Age));  
```
I have not touched EF6 in years but this should work for both dates and numeric types. You just need to find a function that converts your type to a desired string. Below is an example for a date types. Dates are a little more complex to handle so please check the [Transact Sql docs](https://docs.microsoft.com/en-us/sql/t-sql/functions/datename-transact-sql). 

```csharp
//Property BirthDate is a DateTime
var parser = new Parser<Person>(p, context.People)
                  .SetConverter(x => x.BirthDate, x => SqlFunctions.DateName("m",x.BirthDate));  
```

**Comment by arbh89** [comment]
It is orking now, but this is a litle bit tricky.

Thank you.

**Comment by garvincasimir** [comment]
Can you share your final solution? I will add a section to the docs for EF6 once you confirm what works.

**Comment by garvincasimir** [comment]
I agree. It can get tedious if you have many numeric and date type fields. However, I bet it is a lot less painful than creating your own parser.

This current implementation allows me to support a wider range of scenarios. For example, I don't know how you format your dates or numbers, whether you put leading zeros in front of your numbers. You may also have different formatting for properties of the same type. For example one date only shows the year and another shows a numeric representation.
