### ISSUE TITLE
Usage of Select2

### ISSUE THREAD

**Issue by eynarhaji** [garvincasimir/csharp-datatables-parser#31]
Dear,

I cannot use select2 filter option with your parse plugin, because datatables cannot fetch data of columns. I am using Yadcf for filtering. How can I fetch data from table for Yadcf Select2 filter?

**Comment by garvincasimir** [comment]
Hi @eynarhaji, I am not familiar with select2 or Yadcf. Can you post the entire GET/POST request being sent to the parser? Also, I am not sure what you mean by "fetch data of columns".

**Comment by garvincasimir** [comment]
As far as I can tell, this returned JSON is for populating the dropdowns and not for actual table data. In general, the parser is only intended to support the input and output expected by DataTables. Any custom plugin functionality can be done in your own personal fork of the project.
