### ISSUE TITLE
AmbiguousMatchException: Ambiguous match found.

### ISSUE THREAD

**Issue by mhd-haddad** [garvincasimir/csharp-datatables-parser#36]
Hi 
after upgrade to core 2.2.1 , search on datatable not work , always give this error 

An unhandled exception occurred while processing the request.
AmbiguousMatchException: Ambiguous match found.
System.RuntimeType.GetMethodImplCommon(string name, int genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)

![image](https://user-images.githubusercontent.com/42977813/52283859-5a555e00-2974-11e9-987f-1392a85d06c5.png)

**Comment by garvincasimir** [comment]
What does the full line look like? It should be the following:
    `var globalTest = Expression.Call(toLower, typeof(string).GetMethod(globalFilterFn, new[] { typeof(string) }), globalFilterConst);`

https://github.com/garvincasimir/csharp-datatables-parser/blob/master/src/DatatablesParser/DatatablesParser.cs#L362
