### ISSUE TITLE
No properties were found in request

### ISSUE THREAD

**Issue by IwanSumpena** [garvincasimir/csharp-datatables-parser#41]
I get error "No properties were found in request. Please map datatable field names to properties in T"

**Comment by garvincasimir** [comment]
You may not be setting things up correctly on the client side. The column property names on the JavaScript side should match this in the type supplied as the generic parameter on the server side. Please see the sample project in this repo for an example.

**Comment by IwanSumpena** [comment]
i follow setting like repo but i get error 
![image](https://user-images.githubusercontent.com/29264028/66971508-b653b300-f0bb-11e9-9f4c-0185fb948626.png)

**Comment by garvincasimir** [comment]
Can you post your datatables client and server side configuration?

**Comment by IwanSumpena** [comment]
this is index.cshtml
![image](https://user-images.githubusercontent.com/29264028/66982575-9edaf100-f0e0-11e9-8ea8-48d518934f3a.png)

this is my function
![image](https://user-images.githubusercontent.com/29264028/66982657-d3e74380-f0e0-11e9-816f-5986f57f4f11.png)

this is my DbContext
![image](https://user-images.githubusercontent.com/29264028/66982691-e5c8e680-f0e0-11e9-891f-94414f792b7e.png)

this is Class
![image](https://user-images.githubusercontent.com/29264028/66982719-f6795c80-f0e0-11e9-809b-59da470e73d3.png)

is there anything missing from my code ?
i am a newbee

**Comment by garvincasimir** [comment]
Did you make the recommended changes in startup.cs? What is the actual http response that caused that error? There should be more detail in the browser's developer tools console.

**Comment by IwanSumpena** [comment]
Owh yes .ok apparently the code is lacking. Now it's not error

thank you .
