### ISSUE TITLE
how can i make it work with ASP.NET Core Razor Pages

### ISSUE THREAD

**Issue by orok83** [garvincasimir/csharp-datatables-parser#42]
Hello,
Is it possible to make it work with ASP.NET Core Razor Pages.
Thank you for your effort

**Comment by garvincasimir** [comment]
Have you tried it and encountered an issue? The library is intended to be very framework agnostic. 

- The constructor accepts the request parameters and an IQueryable. 
- The Parse method returns the json output expected by the js client library.
