### ISSUE TITLE
Please upgrade to Core 3.0

### ISSUE THREAD

**Issue by januszj** [garvincasimir/csharp-datatables-parser#43]
Hi,
First let me thank you for your code, I'm using it in my hobby project and it was very useful with core 2.2.
For core 3.0 I'm facing issue related to the breaking changes in ef core 3.0: https://go.microsoft.com/fwlink/?linkid=2101038

Thanks !

**Comment by januszj** [comment]
Additional details, I run on this error, when sorting and searching: 

> The LINQ expression could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

**Comment by januszj** [comment]
OK, at least my issue is resolved now. I was not using this in my column definition:
`{ data: "BirthDateFormatted", title: "Birth Date", orderData: 3 }`
it worked with ef 2.2 but probably result was full translation on server. Ef 3.0 simply did not want to cooperate :) 
This is good, only problem is there is no way to figure out what is wrong from the message, so finding source of issue is fully step by step manual process of elimination. 
This issue is closed.

**Comment by garvincasimir** [comment]
The library requires no changes to work with 3.0. You will see that I have tried to update the test project to work with 3.0. I need to figure out why all tests are not passing.

**Comment by januszj** [comment]
Yes, I confirm. The only problem I had was using formatted dates for sorting/searching - this failed as ef core 3.0 does not do client evaluation anymore.
