### ISSUE TITLE
Ability to add row delete button

### ISSUE THREAD

**Issue by christopher-graham** [garvincasimir/csharp-datatables-parser#44]
Hi, I am trying to add a delete button on each row. Is there a way to do this?

**Comment by garvincasimir** [comment]
Yes this can be done. Please take a look at the datatables docs and ask in their forum. 

One way to do it is inject the delete button into a row using a callback. You will need to expose an endpoint that accepts the id if the row you want to delete and performs the necessary actions.

https://datatables.net/reference/option/rowCallback
