### ISSUE TITLE
Is this support netcoree 3.1?

### ISSUE THREAD

**Issue by arhen** [garvincasimir/csharp-datatables-parser#45]
I got error 
```json
The type or namespace name 'DataTablesParser' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by garvincasimir** [comment]
I can't think of any reason why it wouldn't work. Did you import the NuGet package?

**Comment by arhen** [comment]
Its error when I publish with every  target build except portable

**Comment by garvincasimir** [comment]
The library is only one file. I suggest just copying the code into your project and see if it works.

**Comment by arhen** [comment]
I see, Ill close it now. Thanks

**Comment by earllocker** [comment]
I ran into an issue with .NET Core 3.1. If using a boolean field in your filter, the conversion ToString() in the GenerateEntityFilter function will cause an exception as it cannot properly be translated on the server. I think it's caused by this issue: https://github.com/dotnet/efcore/issues/14205

**Comment by garvincasimir** [comment]
You can probably exclude Boolean from search so it won’t get added to the where clause. Do you search for strings “true” and “false”?

**Comment by earllocker** [comment]
I have boolean fields that need to be filtered so will have to find a workaround. It doesn't matter if I search for "true" and "false" or "0" and "1" (which worked in .NET Core 2.2). The ToString() function on a boolean will cause evaluation on the client. At least in my testing. You can try a where clause similar to .Where(x => x.boolField.ToString().Equals("true")) on the iQueryable before sending it to the DataTables Parser and it will produce the same exception.

**Comment by garvincasimir** [comment]
You can find another built-in function that will convert a Boolean to a string then put that in a UDF. Once that is done you can replace the toString() call on your Boolean fields.
