### ISSUE TITLE
JavaScriptSerializer MaxJsonLength Value

### ISSUE THREAD

**Issue by sekmenhuseyin** [garvincasimir/csharp-datatables-parser#48]
Hi,

In one of my ASP.Net 4.7 projects I am geting this error:
`System.InvalidOperationException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.`

I have tried web config changes but didn't work. There is another solution which I need help doing.
```
var serializer = new JavaScriptSerializer();
serializer.MaxJsonLength = Int32.MaxValue;
```
I have to write this code in my class but that won't change your serializer settings.

Is there a way to change maxJsonLength value?

**Comment by garvincasimir** [comment]
This really depends on the version of ASP.net you are using. The library doesn't do serialization/deserialization. It is handled in your controller when you use JsonResult. Please do some more research on how this can be configured. You also have the option of not using JsonResult and serializing the result yourself. 

As a side note, if you are getting this error you are probably returning more data than can be rendered on the screen. I recommend keeping your page size small.
