### ISSUE TITLE
Is this support Regex search?

### ISSUE THREAD

**Issue by arhen** [garvincasimir/csharp-datatables-parser#49]
Something like search for:
a. %data% 
which is search for any match string contains data before and after that string.
b. download|upload
 whis is search for data contains download OR upload string

**Comment by garvincasimir** [comment]
Option a. is the default search behavior. This means any search always tries to find the search string in any part of the field. You can also do begins with and ends with (please consult the readme). Unfortunately regex is not supported.

**Comment by arhen** [comment]
> Option a. is the default search behavior. This means any search always tries to find the search string in any part of the field. You can also do begins with and ends with (please consult the readme). Unfortunately regex is not supported.

is there any support for regex in the future?

![image](https://user-images.githubusercontent.com/15151850/101894333-fee3ff00-3be0-11eb-84d7-4f500c22b878.png)

I've built dynamic dropdown search on each columns like image above. For now, I just make it as radio button, but actually I want to make it as checkbox(I did it) and send array value like point (b) to server. I can achieve this with regex search on client side rendering but when it comes to Server-side, it does not work.

**Comment by arhen** [comment]
for context,
[Regex search docs on datatable](https://datatables.net/examples/api/regex.html)

**Comment by garvincasimir** [comment]
I could implement regex but there just isn't good support for it on the database side. I suppose it can be done for in
Memory data (Object Query). Also, in theory, exposing regex on the client side intended for execution on the server said leaves you open to easy DDOS.
