### ISSUE TITLE
Target .NET Standard 2.0 and 2.1 

### ISSUE THREAD

**Issue by NikolayIT** [garvincasimir/csharp-datatables-parser#50]

**Comment by garvincasimir** [comment]
Hey @NikolayIT can you provide some details for this issue?

**Comment by NikolayIT** [comment]
Hello @garvincasimir 
you are tarrgeting .NET Standard 1.6 for your great library but it downloads a lot of dependencies when installing on .NET 5.0. If you add a target to .NET Standard 2.0 or 2.1 or target .NET Core 5.0 directly there will be no additional packages downloaded and installed as dependency to your library.

**Comment by garvincasimir** [comment]
Now targets 2.0

**Comment by NikolayIT** [comment]
Thank you very much! An upload to NuGet would be great. :)

**Comment by weedkiller** [comment]
Can you also provide .NET core 5 and [.NET Core 6.](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/)

The old targets are not supported anymore if you get a new win10 20H11 OS laptop they all dont let you downgrade.

BTW this is cool too.. https://github.com/grid-js/gridjs

**Comment by garvincasimir** [comment]
@weedkiller if I understand the .net versioning scheme correctly, the net standard 2.0 target should be sufficient for those platform versions. Please let me know if I am missing something.

**Comment by NikolayIT** [comment]
Do you plan to upload it to NuGet :)

**Comment by garvincasimir** [comment]
Should be up there now

**Comment by NikolayIT** [comment]
Thank you so much! And do you plan to update the dependencies to newer versions :)
* Microsoft.Extensions.Primitives
* System.Linq.Queryable
* System.Reflection.TypeExtensions

**Comment by weedkiller** [comment]
There quite a few dependencies that are different in .NET 5 & 6, like EF Core/EF 6 and mainly nugets and such. I am migrating something now, and I will let you know what I find.

BTW your parser is Awesome!

**Comment by garvincasimir** [comment]
@NikolayIT I can change this but if you are using newer versions in your project those take priority: https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#nearest-wins

**Comment by garvincasimir** [comment]
@weedkiller The library doesn't take a direct dependency on entity framework so  we should be ok there. It is designed to work with any IQueryable.

**Comment by garvincasimir** [comment]
@NikolayIT  are we ok to close this issue?

**Comment by NikolayIT** [comment]
Yes, thanks.
