### ISSUE TITLE
TagHelper/ViewComponent for parser

### ISSUE THREAD

**Issue by weedkiller** [garvincasimir/csharp-datatables-parser#51]
It would be nice to have a tagHelper with this.

Here is a [sample code.. ](https://github.com/jqwidgets/AspNetCore-Mvc-Tag-Helpers/blob/master/README.md)

**Comment by garvincasimir** [comment]
Hey @weedkiller Unfortunately I cannot commit to a time required to do this but I would be happy for a contribution￼.
